/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppReturnsRouteImport } from './routes/app.returns'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppProcurementRouteImport } from './routes/app.procurement'
import { Route as AppLogisticsRouteImport } from './routes/app.logistics'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppForecastingRouteImport } from './routes/app.forecasting'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppReturnsIndexRouteImport } from './routes/app.returns.index'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppReturnsHistoryRouteImport } from './routes/app.returns.history'
import { Route as AppProductsSkuRouteImport } from './routes/app.products.$sku'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppLogisticsRoute = AppLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppForecastingRoute = AppForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsIndexRoute = AppReturnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReturnsRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppReturnsHistoryRoute = AppReturnsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppReturnsRoute,
} as any)
const AppProductsSkuRoute = AppProductsSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => AppProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/products/$sku': typeof AppProductsSkuRoute
  '/app/returns/history': typeof AppReturnsHistoryRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/returns/': typeof AppReturnsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/reports': typeof AppReportsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/products/$sku': typeof AppProductsSkuRoute
  '/app/returns/history': typeof AppReturnsHistoryRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/returns': typeof AppReturnsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/forecasting': typeof AppForecastingRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/logistics': typeof AppLogisticsRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/returns': typeof AppReturnsRouteWithChildren
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/products/$sku': typeof AppProductsSkuRoute
  '/app/returns/history': typeof AppReturnsHistoryRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/returns/': typeof AppReturnsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/forecasting'
    | '/app/inventory'
    | '/app/logistics'
    | '/app/procurement'
    | '/app/products'
    | '/app/reports'
    | '/app/returns'
    | '/app/suppliers'
    | '/app/products/$sku'
    | '/app/returns/history'
    | '/app/products/'
    | '/app/returns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/forecasting'
    | '/app/inventory'
    | '/app/logistics'
    | '/app/procurement'
    | '/app/reports'
    | '/app/suppliers'
    | '/app/products/$sku'
    | '/app/returns/history'
    | '/app/products'
    | '/app/returns'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/copilot'
    | '/app/dashboard'
    | '/app/forecasting'
    | '/app/inventory'
    | '/app/logistics'
    | '/app/procurement'
    | '/app/products'
    | '/app/reports'
    | '/app/returns'
    | '/app/suppliers'
    | '/app/products/$sku'
    | '/app/returns/history'
    | '/app/products/'
    | '/app/returns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/returns': {
      id: '/app/returns'
      path: '/returns'
      fullPath: '/app/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logistics': {
      id: '/app/logistics'
      path: '/logistics'
      fullPath: '/app/logistics'
      preLoaderRoute: typeof AppLogisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/forecasting': {
      id: '/app/forecasting'
      path: '/forecasting'
      fullPath: '/app/forecasting'
      preLoaderRoute: typeof AppForecastingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/returns/': {
      id: '/app/returns/'
      path: '/'
      fullPath: '/app/returns/'
      preLoaderRoute: typeof AppReturnsIndexRouteImport
      parentRoute: typeof AppReturnsRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/returns/history': {
      id: '/app/returns/history'
      path: '/history'
      fullPath: '/app/returns/history'
      preLoaderRoute: typeof AppReturnsHistoryRouteImport
      parentRoute: typeof AppReturnsRoute
    }
    '/app/products/$sku': {
      id: '/app/products/$sku'
      path: '/$sku'
      fullPath: '/app/products/$sku'
      preLoaderRoute: typeof AppProductsSkuRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppProductsRouteChildren {
  AppProductsSkuRoute: typeof AppProductsSkuRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsSkuRoute: AppProductsSkuRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppReturnsRouteChildren {
  AppReturnsHistoryRoute: typeof AppReturnsHistoryRoute
  AppReturnsIndexRoute: typeof AppReturnsIndexRoute
}

const AppReturnsRouteChildren: AppReturnsRouteChildren = {
  AppReturnsHistoryRoute: AppReturnsHistoryRoute,
  AppReturnsIndexRoute: AppReturnsIndexRoute,
}

const AppReturnsRouteWithChildren = AppReturnsRoute._addFileChildren(
  AppReturnsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppForecastingRoute: typeof AppForecastingRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLogisticsRoute: typeof AppLogisticsRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppReturnsRoute: typeof AppReturnsRouteWithChildren
  AppSuppliersRoute: typeof AppSuppliersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppForecastingRoute: AppForecastingRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLogisticsRoute: AppLogisticsRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppReturnsRoute: AppReturnsRouteWithChildren,
  AppSuppliersRoute: AppSuppliersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
